version: "3.3"
services:
  nyaspeed:
    restart: always
    image: nyawork/nyaspeed
    #build: .
    volumes:
      - "./settings.toml:/app/settings.toml:ro"
      - "./GeoIP2-City.mmdb:/app/GeoIP2-City.mmdb:ro"
    ports:
      - "127.0.0.1:8989:8989"